export const ADD_INGREDIENT = "ADD_INGREDINET";
export const REMOVE_INGREDIENT = "REMOVE_INGREDINET";
export const FETCH_INGREDIENTS_INPROGRESS = "FETCH_INGREDIENTS_PROGRESS";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const SET_PRESERVE_INGREDIENTS = "SET_PRESERVE_INGREDIENTS";
export const PRESERVED_INGREDINETS_SUCCESS = "PRESERVED_INGREDINETS_SUCCESS";

export const PLACE_ORDER_INIT = "PLACE_ORDER_INIT";
export const PLACE_ORDER_INPROGRESS = "PLACE_ORDER_INPROGRESS";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_INPROGRESS = "FETCH_ORDERS_INPROGRESS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_INIT = "AUTH_INIT";
export const AUTH_INPROGRESS = "AUTH_INPROGRESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";
