// BurgerBuilder
export const ADD_INGREDIENT = "ADD_INGREDINET";
export const REMOVE_INGREDIENT = "REMOVE_INGREDINET";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// Checkout
export const PLACE_ORDER_INIT = "PLACE_ORDER_INIT";
export const PLACE_ORDER_INPROGRESS = "PLACE_ORDER_INPROGRESS";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

// Orders
export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_INPROGRESS = "FETCH_ORDERS_INPROGRESS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
