// DosaBuilder
export const ADD_INGREDIENT = "ADD_INGREDINET";
export const REMOVE_INGREDIENT = "REMOVE_INGREDINET";
export const FETCH_INGREDIENTS_INIT = "FETCH_INGREDIENTS_INIT";
export const FETCH_INGREDIENTS_INPROGRESS = "FETCH_INGREDIENTS_INPROGRESS";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// Order
export const PLACE_ORDER_INIT = "PLACE_ORDER_INIT";
export const PLACE_ORDER_INPROGRESS = "PLACE_ORDER_INPROGRESS";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";
export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_INPROGRESS = "FETCH_ORDERS_INPROGRESS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
